# Generated by Django 5.0.6 on 2024-06-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.CharField(
                choices=[
                    ("TC", "Tecnologia"),
                    ("CR", "Curiosidades"),
                    ("GR", "Gerais"),
                ],
                default="GR",
                max_length=2,
            ),
        ),
    ]
