# Generated by Django 5.0.6 on 2024-06-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts"),
        ),
    ]
